fc5y/user-fe

.babelrc, .eslintrc.json, package-lock.json, package.json, public/index.html, src/app/components/HomePage/index.js, src/utils/config.js, src/utils/fetchUtils.js, src/utils/getUrl.js, webpack/config.js, webpack/webpack.config.js, webpack/webpack.dev.js, webpack/webpack.prod.js
* Add fetch utils and webpack proxy
* Fix error webpack setting conflicts with nested routes
=> Add fetch utils

package-lock.json, package.json, src/app/App.js, src/app/components/Button/btnLoginAndSignup.scss, src/app/components/InfoPage/Content.js, src/app/components/InfoPage/Info.md, src/app/components/InfoRulesPage/Content.js, src/app/components/InfoRulesPage/Info.md, src/app/components/InfoRulesPage/content.scss, src/app/components/InfoRulesPage/index.js, src/app/style.scss, webpack/webpack.dev.js, webpack/webpack.prod.js
Create InfoRulesPage and add text. I branched out this one from 'hieu.vo/edit/InfoPage'.
=> Add info rules page

src/app/components/HomePage/Content.js, src/app/components/HomePage/Info.md, src/app/components/HomePage/content.scss, src/app/components/InfoPage/Content.js, src/app/components/InfoPage/Info.md, src/app/components/InfoPage/content.scss, src/app/components/InfoRulesPage/Content.js, src/app/components/InfoRulesPage/Info.md, src/app/components/InfoRulesPage/content.scss
=> Add text to HomePage

src/app/containers/InfoPage/Info.md, src/app/containers/InfoPage/style.scss, src/app/containers/InfoRulesPage/Info.md, src/app/containers/InfoRulesPage/style.scss
=> Edit markdown files

src/app/containers/LoginPage/index.js, src/shared/context/UserInfo.js
Resolve issue https://github.com/fc5y/user-fe/issues/56
=> Fix issue cannot login after Popup PR merged

src/app/containers/EnterPage/index.js, src/app/containers/HomePage/index.js
Call API to disable/activate enter button and access enter page.
=> Call API to disable/activate enter button and access enter page.

src/app/common-ui/Popup/index.js, src/app/containers/LoginPage/index.js
=> Fix Popup cross-browser issue

src/app/common-ui/Loading/style.scss, src/app/common-ui/Popup/index.js, src/app/common-ui/Popup/style.scss, src/app/containers/LoginPage/index.js
* Update logic of Popup component to be transparent.
=> Update popup with cleaner logic

jsconfig.json, package-lock.json, package.json, src/app/common-ui/Loading/index.js, src/app/common-ui/Popup/index.js, src/app/components/NavBar/index.js, src/app/containers/CmsHelpPage/content.md, src/app/containers/InfoPage/index.js, src/app/containers/JoinHelpPage/content.md, webpack/config.js, webpack/webpack.common.js, webpack/webpack.dev.js, webpack/webpack.prod.js
* Fix error loading static assets
=> Fix static assets

src/api/user.js, src/app/containers/ChangePassword/index.js, src/app/containers/ChangePassword/validators.js, src/app/routes/constants.js, src/app/routes/routes.js
- Add change password page
- Add change password route
=> Add change password page

src/app/containers/LoginPage/index.js, src/app/containers/LoginPage/styles.scss
Remove logo and move sign up to logo position
=> Remove logo and move sign up to logo position

src/app/common-ui/Button/style.scss, src/app/containers/SignupPage/EmailOTP/index.js, src/app/containers/SignupPage/EnterScreen/index.js
- Edit signup enter screen UI
- Edit Email OTP UI
=> Edit signup page UI

src/app/containers/Contests/ContestRegister/components/RegisterForm/index.js, src/app/containers/PolicyPage/index.js, src/app/containers/SignupPage/EnterScreen/index.js, src/app/routes/constants.js, src/app/routes/routes.js
=> Add policy page

src/app/containers/PolicyPage/index.js
=> Change policy title font-size

src/app/common-ui/AlertWarning/index.js, src/app/containers/HomePage/index.js
=> Add AlertWarning

src/app/containers/MigrationPlan/index.js, src/app/routes/constants.js, src/app/routes/routes.js
=> Add Migration Plan

src/app/containers/LoginPage/index.js
=> Fix forgot password UI bug

src/app/common-ui/DropdownButton/index.js, src/app/components/ContestActionButton/index.js
Fix wrong Contest Action Button Dropdown material behaviour
=> Fix wrong Contest Action Button Dropdown material behaviour

package-lock.json, package.json, webpack/webpack.common.js
* Enabling compression in webpack
* Before: 428 KB
* After: 128 KB
=> Add compresion in webpack with gzipped files

.eslintrc.json, .gitattributes, .vscode/settings.json, package.json, src/api/contest.js, webpack/webpack.common.js, webpack/webpack.config.js
Fix Issue window starting script due to new line break of window developers
=> Fix error linebreak and starting script for window developers

src/app/containers/HomePage/components/Announcements/index.js
Fix bug of pr https://github.com/fc5y/user-fe/pull/176
=> Fix bug of pr #176

src/api/authentication.js, src/app/components/EmailOTP/index.js, src/app/components/EmailOTP/validators.js, src/app/containers/SettingsPage/config.js, src/app/containers/SettingsPage/index.js, src/app/containers/SignupPage/index.js
- Add email updating features
- Refactor code in signup (move EmailOTP from containers to components)
=> Add email updating features and refactor code
